name: 🐞 Bug
description: File a bug/issue
title: "bug(scope): "
labels: ["bug"]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **reNgine**: 1.3.6
        - **OS**: Ubuntu 20.04
        - **Python**: 3.11.0
        - **Docker**: 20.10.22
        - **Docker compose**: 2.15.1
        - **Browser**: Microsoft Edge 112.0.1722.58
    value: |
        - reNgine: 
        - OS: 
        - Python: 
        - Docker Engine: 
        - Docker Compose: 
        - Browser: 
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  id: acknowledgements
  attributes:
    label: Acknowledgements
    description: Your bug report will be closed if you don't follow the checklist below.
    options:
      - label: This issue is not a duplicate of an existing bug report.
        required: true
      - label: I have chosen an appropriate title.
        required: true
      - label: All requested information has been provided properly.
        required: true
